[tool.poetry]
name = "flatmapknowledge"
version = "1.6.2"
description = ""
authors = ["David Brooks <d.brooks@auckland.ac.nz>"]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
mapknowledge = {url = "https://github.com/AnatomicMaps/map-knowledge/releases/download/v0.16.2/mapknowledge-0.16.2-py3-none-any.whl"}
